import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillGithub,
  AiFillLinkedin,
} from "react-icons/ai";
import Image from "next/image";
import anish from "../public/anish.jpg";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Anish Soni</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-zinc-950 px-10 md:px-20 lg:pfd-40 text-white">
        <section className="min-h-screen pb-20">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons">Developed by Anish</h1>
            <ul className="flex items-center">
              <li>
                <a
                  className="bg-green-600 text-white px-4 py-2 rounded-md ml-8"
                  href="/resume_anish_soni.pdf"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 text-white">
            <h2 className="text-5xl py-2 text-[#b7b499] font-medium md:text-6xl dark:text-[#CCC8AA]">
              Anish Soni
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl text-white">
              Engineer | Designer | Developer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-400 md:text-xl max-w-xl mx-auto">
              A computer geek who is experimenting with Advanced Computing,
              Artificial intelligence, Machine learning, and Design.
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-400">
            <a
              href="https://github.com/anishsoni29"
              target="_blank"
              div
              className="cursor-pointer text-white hover:scale-110 transition-transform"
            >
              <AiFillGithub />
            </a>
            <a
              href="https://www.linkedin.com/in/anishsoni/"
              target="_blank"
              div
              className="cursor-pointer text-blue-600 hover:scale-110 transition-transform"
            >
              <AiFillLinkedin />
            </a>
            <a
              href="https://twitter.com/anishsoni29"
              target="_blank"
              div
              className="cursor-pointer text-blue-400 hover:scale-110 transition-transform"
            >
              <AiFillTwitterCircle />
            </a>
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-text-[#CCC8AA] rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96 dark:bg-white hover:scale-110 transition-transform">
            <Image src={anish} layout="fill" objectFit="cover" />
          </div>
        </section>
        <section>
          <div>
            <button
              type="button"
              class="text-white bg-gray-800 hover:bg-gray-900 focus:outline-none focus:ring-4 focus:ring-gray-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-gray-800 dark:hover:bg-gray-700 dark:focus:ring-gray-700 dark:border-gray-700 mb-10"
            >
              Services
            </button>
            <p className="text-md py-2 leading-8 text-gray-80 text-white">
              Working on <span className="text-blue-400">Open Source </span>{" "}
              since the beginning of the adventure, and I'm currently extending
              my expertise in{" "}
              <span className="text-blue-400">Artificial Intelligence</span>{" "}
              because, well, why not?
            </p>
            <p className="text-md py-2 leading-8 text-gray-80 text-white">
              I have also worked on{" "}
              <span className="text-blue-400">Data Analysis</span> and{" "}
              <span className="text-blue-400"> Map Designs</span> and have built
              some cool projects.
            </p>
          </div>
          <div className="lg:flex gap-10 ">
            <div className="bg-gray-800 opacity-70 text-center shadow-lg p-10 rounded-xl my-10 flex-1 hover:scale-110 transition-transform">
              <div className="flex flex-col items-center">
                <div className="image-container">
                  <Image src={design} width={100} height={100} />
                </div>
                <h3 className="text-lg font-medium pt-8 pb-2">
                  Beautiful Designs
                </h3>
                <p className="py-2">Creating elegant designs.</p>
                <h4 className="py-4 text-green-600">Design Tools I use:</h4>
                <p className="text-gray-600 py-1">Photoshop</p>
                <p className="text-gray-600 py-1">Figma</p>
                <p className="text-gray-600 py-1">Illustrator</p>
                <p className="text-gray-600 py-1">Photoshop</p>
              </div>
            </div>
            <div className="bg-gray-800 opacity-70 text-center shadow-lg p-10 rounded-xl my-10 flex-1 hover:scale-110 transition-transform">
              <div className="flex flex-col items-center">
                <Image src={code} width={100} height={100} />
                <h3 className="text-lg font-medium pt-8 pb-2">Code</h3>
                <p className="py-2">Producing refined code on a daily basis.</p>
                <h4 className="py-4 text-green-600">Domains:</h4>
                <p className="text-gray-600 py-1">Data Science</p>
                <p className="text-gray-600 py-1">Machine Learning</p>
                <p className="text-gray-600 py-1">Artificial Intelligence</p>
                <p className="text-gray-600 py-1">Statistics</p>
              </div>
            </div>
            <div className="bg-gray-800 opacity-70 text-center shadow-lg p-10 rounded-xl my-10 flex-1 hover:scale-110 transition-transform">
              <div className="flex flex-col items-center">
                <Image src={consulting} width={100} height={100} />
                <h3 className="text-lg font-medium pt-8 pb-2">
                  Brain - Storming
                </h3>
                <p className="py-2">Extra-curricular Interests!</p>
                <h4 className="py-4 text-green-600">Favourites:</h4>
                <p className="text-gray-600 py-1">Finance & Economics</p>
                <p className="text-gray-600 py-1">Fitness</p>
                <p className="text-gray-600 py-1">Ergonomics and Design</p>
                <p className="text-gray-600 py-1">
                  Bussiness & Political Case Studies
                </p>
              </div>
            </div>
          </div>
        </section>
        <section>
          <div>
            <button
              type="button"
              className="text-white bg-gray-800 hover:bg-gray-900 focus:outline-none focus:ring-4 focus:ring-gray-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-gray-800 dark:hover:bg-gray-700 dark:focus:ring-gray-700 dark:border-gray-700 mb-10"
            >
              Portfolio
            </button>
            <div className="text-md py-2 leading-8 text-gray-200">
              <div className="text-green-400">console.log</div>
              Thanks for diving into my digital world !; <br />
              Keep coding, keep creating, and let's innovate together !; <br />
            </div>
          </div>
        </section>
        <footer className="rounded-lg shadow m-4 bg-gray-800">
          <div className="w-full mx-auto max-w-screen-xl p-4 md:flex md:items-center md:justify-between">
            <span class="text-sm text-gray-500 sm:text-center dark:text-gray-400">
              © 2024 <a class="hover:underline">Anish Soni</a>
            </span>
            <ul className="flex flex-wrap items-center mt-3 text-sm font-medium text-gray-500 dark:text-gray-400 sm:mt-0">
              <li className="ml-2">
                <a
                  href="https://www.linkedin.com/in/anishsoni/"
                  target="_blank"
                  className="hover:text-blue-500 mr-3"
                >
                  LinkedIn
                </a>
              </li>
              <li class="ml-2">
                <a
                  href="https://github.com/anishsoni29"
                  target="_blank"
                  className="hover:text-green-300 mr-3"
                >
                  Github
                </a>
              </li>
              <li className="ml-2">
                <a
                  href="https://www.instagram.com/depolarised_/"
                  target="_blank"
                  className="hover:text-pink-400 mr-3"
                >
                  Photography
                </a>
              </li>
              <li className="ml-2">
                <a
                  href="https://twitter.com/anishsoni29"
                  target="_blank"
                  className="hover:text-blue-300 mr-3"
                >
                  Twitter
                </a>
              </li>
            </ul>
          </div>
        </footer>
      </main>
    </div>
  );
}
